import React,{useEffect,useState} from 'react'
import {X} from 'lucide-react'
import {supabase} from '../supabase.js'
import {useBusinessContext} from './businessConfig.js'
import {businessDateKey,mondayForDate,todayAppointments,clientConfirmationStatus,openSms,normalizedPhone} from './shared.jsx'
import {nextDate,reminderText,reminderEligible} from './reminderQueue.js'
export default function ReminderQueue({dogs,revision,onClose}){
 const business=useBusinessContext(),today=businessDateKey(),[date,setDate]=useState(nextDate(today)),[rows,setRows]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[refresh,setRefresh]=useState(0),[groomer,setGroomer]=useState('All'),[unconfirmed,setUnconfirmed]=useState(false),[drafts,setDrafts]=useState({}),[notice,setNotice]=useState('')
 useEffect(()=>{let live=true;setLoading(true);setError('');setDrafts({});setNotice('');supabase.from('weekly_drafts').select('plan_json').eq('business_id',business.businessId).eq('week_start',mondayForDate(date)).limit(1).then(({data,error})=>{if(!live)return;if(error)setError('Could not load reminders. Please try again.');else setRows(data?.[0]?.plan_json||[])}).catch(()=>{if(live)setError('Could not load reminders. Please try again.')}).finally(()=>{if(live)setLoading(false)});return()=>{live=false}},[date,business.businessId,revision,refresh])
 if(business.role!=='owner')return null
 const appts=todayAppointments(rows,date,groomer,dogs).filter(a=>reminderEligible(a.sourceRow)&&(!unconfirmed||clientConfirmationStatus(a.sourceRow)!=='Confirmed'))
 return <div className="sheet-backdrop" onClick={onClose}><section className="sheet" role="dialog" aria-modal="true" aria-labelledby="reminders-title" onClick={e=>e.stopPropagation()} style={{maxHeight:'92dvh',overflow:'auto',padding:20}}>
 <style>{`.reminder-queue-fields{display:flex;gap:12px;flex-wrap:wrap}.reminder-queue-fields label{display:grid;gap:6px;flex:1;min-width:130px}.reminder-queue-fields input,.reminder-queue-fields select,.reminder-queue-text{width:100%;box-sizing:border-box;font:inherit;padding:12px;border:1px solid #dce1ea;border-radius:12px;background:white;color:#172038}.reminder-queue-text{min-height:120px;margin:10px 0}.reminder-queue-card{padding:14px;border:1px solid #e1e4e9;border-radius:16px;margin:12px 0}.reminder-queue-card p{font-size:12px;color:#657084}`}</style>
 <div style={{display:'flex',justifyContent:'space-between',gap:12}}><div><div className="eyebrow">BUSINESS</div><h2 id="reminders-title">Client reminders</h2></div><button className="icon-btn" aria-label="Close reminders" onClick={onClose}><X/></button></div>
 <p>Send from your existing business number. Review a reminder, open Messages, then tap Send. Replies stay in your phone’s Messages app.</p>
 <div className="reminder-queue-fields"><label>Appointment day<input type="date" min={today} value={date} onChange={e=>{if(e.target.value>=today)setDate(e.target.value)}}/></label><label>Groomer<select value={groomer} onChange={e=>setGroomer(e.target.value)}><option>All</option>{business.settings.groomers.map(g=><option key={g.id}>{g.name}</option>)}</select></label></div>
 <label style={{display:'flex',alignItems:'center',gap:8,margin:'14px 0'}}><input type="checkbox" checked={unconfirmed} onChange={e=>setUnconfirmed(e.target.checked)}/>Only clients needing confirmation</label>
 {loading?<p role="status">Loading appointments…</p>:error?<p role="alert">{error}<button className="secondary-btn" onClick={()=>setRefresh(n=>n+1)}>Retry</button></p>:<><strong>{appts.length} reminder{appts.length===1?'':'s'} to review</strong>{!appts.length&&<p>No upcoming appointments match this selection.</p>}{appts.map(a=>{const body=drafts[a.id]??reminderText(a,business.settings.businessName);return <article key={a.id} className="reminder-queue-card"><strong>{a.owner} · {a.time||'Time to be arranged'}</strong><p>{a.groomer} · {clientConfirmationStatus(a.sourceRow)}</p><label>Reminder text<textarea className="reminder-queue-text" maxLength={1600} value={body} onChange={e=>setDrafts({...drafts,[a.id]:e.target.value})}/></label>{!normalizedPhone(a.phone)&&<p>Add this client’s phone number in Clients before texting.</p>}<button className="secondary-btn" disabled={!normalizedPhone(a.phone)||!body.trim()} onClick={()=>{setNotice('Messages opened. Hey Betty cannot verify whether you sent the text.');openSms(a.phone,body)}}>Open reminder in Messages</button></article>})}</>}
 {notice&&<p role="status">{notice}</p>}<p style={{fontSize:12,color:'#657084'}}>Opening Messages does not mark an appointment confirmed or a reminder sent. Your phone’s selected sending line is used.</p>
 </section></div>
}
